data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  augment_dir: "data/processed_aug"
  img_size: 64
  seq_len: 20
  split:
    train: 0.7
    val: 0.15
    test: 0.15
training:
  batch_size: 16
  epochs: 30
  lr: 0.001
  weight_decay: 1e-5
  early_stopping_patience: 5
model:
  type: "cnn_lstm"
  cnn_lstm:
    cnn_filters: [16, 32, 64]
    lstm_hidden: 128
    lstm_layers: 1
    dropout: 0.5
logging:
  tensorboard_logdir: "runs/"
  model_checkpoint: "checkpoints/"
