# Training Configuration

# Model Architecture
model:
  name: "HandGestureNet"
  input_channels: 3
  num_classes: 10
  hidden_size: 128
  dropout_rate: 0.5
  use_batch_norm: true

# Training Parameters
training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  patience: 5 # Early stopping patience
  optimizer: "adam" # Options: adam, sgd
  scheduler:
    type: "reduce_lr_on_plateau" # Options: reduce_lr_on_plateau, cosine_annealing
    factor: 0.1
    patience: 3
    min_lr: 0.00001

# Data Processing
data:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  augmentation:
    enabled: true
    rotation_range: 15
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]
    horizontal_flip: true
    random_crop:
      enabled: true
      size: [224, 224]
      padding: 4

# Preprocessing
preprocessing:
  image_size: [224, 224]
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  use_grayscale: false

# Hardware
hardware:
  num_workers: 4
  pin_memory: true
  cuda_device: 0

# Logging and Checkpoints
logging:
  save_frequency: 5 # Save model every N epochs
  log_frequency: 100 # Log metrics every N batches
  tensorboard: true
  save_best_only: true
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - confusion_matrix

# Paths
paths:
  data_dir: "./data"
  output_dir: "./results"
  log_dir: "./logs"
  checkpoint_dir: "./checkpoints"

# Debug Mode
debug:
  enabled: false
  subset_size: 100 # Number of samples to use in debug mode
  profile_memory: false
  profile_time: false
